### ISSUE TITLE
Add a productivity > CLI Assistants category?

### ISSUE THREAD

**Issue by itsderek23** [flavienbwk/awesome-llm-devops#3]
First, thanks for this! It's a great resource of what's out there!

I am developing a set of [open benchmarks for DevOps AI Assistants](https://github.com/opstower-ai/devops-ai-open-leaderboard). I noticed that the AI assistants I evaluated aren't on this list and might be nice to add. However, it feels like this would require a new subcategory...basically:

* Productivity
  * CLI Assistants
    * OpsTower.ai (AWS)
    * Release.ai (AWS)
    * Kubectl-GPT
    * Kubectl-gpt
    
Happy to formalize in a PR. Thoughts?

**Comment by flavienbwk** [comment]
Hi @itsderek23 and thank you for your interest in this repo !

I intend this repo to have categories based on features more than human-computer interaction. But! It is a great idea to add this distinction and that's why emojis are here.

I suggest to add the following emojis based on the way to interact with the cited software : 

- :hash: for CLI-interfaced software
- 🖥️ for browser-interfaced software
- 👨‍💻 for IDE-interfaced software

If some assistants do all of these features, only one must be mentioned: the one the product is the most recognized for.

I'll edit the repo with these emojis so you can add the technologies not yet mentioned.

**Comment by flavienbwk** [comment]
Here they are : b7e6d5dccb37e6039c91f3ee6aa4435504e9bbd9

Don't hesitate to contribute with relevant technologies not yet in this repo!

**Comment by itsderek23** [comment]
@flavienbwk - I added the 2 most robust DevOps AI Assistants from the benchmarks in #4.
